name: Build and deploy
on: [push]

env:
  PROJECT_NAME: "random-post"
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_REPO: ${{ secrets.AWS_REPO }}
  DOCKER_REPO_HOST: ${{ secrets.AWS_REPO_HOST }}

jobs:

  pull_and_run_image:
    runs-on: ubuntu-latest
    steps:
      - name: pull and run image
        uses: fifsky/ssh-action@master
        with:
          command: |
            aws ecr get-login-password --region ${{env.AWS_DEFAULT_REGION}} | sudo docker login --username AWS --password-stdin ${{env.DOCKER_REPO_HOST}}
            sudo docker rm -f $(sudo docker ps -a -q --filter ancestor=${{env.DOCKER_REPO_HOST}}:latest --format="{{.ID}}")
            sudo docker pull ${{env.DOCKER_REPO_HOST}}:latest
            cd env
            sudo docker run --env-file 1.env -p 80:8080 ${{env.DOCKER_REPO_HOST}}:latest | exit
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM }}
