name: Build and deploy
on: [push]

env:
  PROJECT_NAME: "random-post"
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_REPO: ${{ secrets.AWS_REPO }}
  DOCKER_REPO_HOST: ${{ secrets.AWS_REPO_HOST }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  KEY: ${{ secrets.PEM }}
jobs:
  pull_image:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to remote server
        run: echo ${KEY} | ssh -i /dev/stdin ${EC2_USER}@${EC2_HOST} command
      - name: aws login, docker login
        run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REPO
      - name: docker pull
        run: docker pull "$DOCKER_REPO:latest"
      - name: docker run
        run: docker run -p 80:8080 $DOCKER_REPO
