name: Build and deploy
on: [push]

env:
  PROJECT_NAME: "random-post"
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_REPO: ${{ secrets.AWS_REPO }}
  DOCKER_REPO_HOST: ${{ secrets.AWS_REPO_HOST }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  KEY: ${{ secrets.PEM }}
jobs:
  pull_image:
    runs-on: ubuntu-latest
    steps:
      - name: enter remote server
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM}}
      - name: login aws
        uses: fifsky/ssh-action@master
        with:
          command: |
            aws ecr get-login-password --region "eu-central-1"
            sudo docker login --username AWS --password-stdin "081430054411.dkr.ecr.eu-central-1.amazonaws.com/random-postcard-ecr-repository"
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM}}
