name: Build and deploy
on: [push]

env:
  PROJECT_NAME: "random-post"
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_REPO: ${{ secrets.AWS_REPO }}
  DOCKER_REPO_HOST: ${{ secrets.AWS_REPO_HOST }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  KEY: ${{ secrets.PEM }}
jobs:
  pull_image:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | sudo docker login --username AWS --password-stdin $DOCKER_REPO
            sudo docker pull "$DOCKER_REPO:latest"
            sudo docker run -p 80:8080 $DOCKER_REPO
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM}}
